# -*- coding: utf-8 -*-
"""Covid Update Bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PlpwIvhJYcU1HCJoLZUEkdICkjCFYjo_
"""

#pip install requests
#pip install win10toast
#Run the above commands in command window.
import requests
import time
from win10toast import ToastNotifier
import json
def update():
  r=request.get('https://coronavirus-19-api.herokuapp.com/all')
  data=r.json()
  text= f'Confirmed Cases: {data["cases"]} \nDeaths: {data["deaths"]} \nRecovered:{data["recovered"]}'

  while True:
    toast=ToastNotifier()
    toast.show_toast("COVID19 UPDATES",text,duration=20)
    time.sleep(60)
update()